# @package _global_
---
defaults:
- override /strategy: fedavgflashback
task:
  dispatch_data:
    heterogeneity: all_clients
    city: CAL
    partition_type: fed_natural
  fit_config:
    net_config:
      h0_seed: 361
      loc_count: 472
      user_count: 1
    dataloader_config:
      loc_count: 472
      batch_size: 1
    run_config:
      loc_count: 472
      batch_size: 1
      client_dropout_probability: 0.15
  eval_config:
    net_config:
      h0_seed: 361
      loc_count: 472
      user_count: 1
    dataloader_config:
      loc_count: 472
      batch_size: 1
    run_config:
      batch_size: 1
  fed_test_config:
    net_config:
      h0_seed: 361
      loc_count: 472
      user_count: 27
    dataloader_config:
      loc_count: 472
      batch_size: 16
    run_config:
      batch_size: 16
  net_config_initial_parameters:
    h0_seed: 361
    loc_count: 472
    user_count: 27
fed:
  num_rounds: 20
  num_total_clients: 27
  num_clients_per_round: 3
  num_evaluate_clients_per_round: 27
